var colorConfigArr = [{
  "paramId": 28975,
  "paramCode": "GT-01",
  "isVisible": "Y",
  "paramName": "时间冲突",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(246, 18, 6)",
  "paramValue1": "rgb(246, 18, 6)",
  "paramValue2": "甘特图",
  "paramValue3": "4",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "甘特条颜色，拖拽底色",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 28976,
  "paramCode": "GT-02",
  "isVisible": "Y",
  "paramName": "可用机位",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(177, 223, 246)",
  "paramValue1": "rgb(177, 223, 246)",
  "paramValue2": "甘特图",
  "paramValue3": "4",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "拖拽底色",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 28977,
  "paramCode": "GT-03",
  "isVisible": "Y",
  "paramName": "廊桥未启用",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(228, 233, 237)",
  "paramValue1": "rgb(228, 233, 237)",
  "paramValue2": "甘特图",
  "paramValue3": "4",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "拖拽底色",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 28978,
  "paramCode": "GT-04",
  "isVisible": "Y",
  "paramName": "机位-航司冲突",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(246, 192, 204)",
  "paramValue1": "rgb(246, 192, 204)",
  "paramValue2": "甘特图",
  "paramValue3": "4",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "拖拽底色",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 28979,
  "paramCode": "GT-05",
  "isVisible": "Y",
  "paramName": "机位-属性冲突",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(255, 212, 222)",
  "paramValue1": "rgb(255, 212, 222)",
  "paramValue2": "甘特图",
  "paramValue3": "4",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "拖拽底色",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 28980,
  "paramCode": "GT-06",
  "isVisible": "Y",
  "paramName": "机位-机型冲突",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(245, 164, 164)",
  "paramValue1": "rgb(245, 164, 164)",
  "paramValue2": "甘特图",
  "paramValue3": "4",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "拖拽底色",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 28981,
  "paramCode": "GT-07",
  "isVisible": "Y",
  "paramName": "机位-任务冲突",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(255, 231, 237)",
  "paramValue1": "rgb(255, 231, 237)",
  "paramValue2": "甘特图",
  "paramValue3": "4",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "拖拽底色",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 28982,
  "paramCode": "GT-08",
  "isVisible": "Y",
  "paramName": "机位-航线冲突",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(205, 238, 141)",
  "paramValue1": "rgb(205, 238, 141)",
  "paramValue2": "甘特图",
  "paramValue3": "4",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "拖拽底色",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 28983,
  "paramCode": "GT-09",
  "isVisible": "Y",
  "paramName": "机位-机号冲突",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(177, 223, 246)",
  "paramValue1": "rgb(177, 223, 246)",
  "paramValue2": "甘特图",
  "paramValue3": "4",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "拖拽底色",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 28984,
  "paramCode": "GT-10",
  "isVisible": "Y",
  "paramName": "机位维护",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(205, 238, 141)",
  "paramValue1": "rgb(205, 238, 141)",
  "paramValue2": "甘特图",
  "paramValue3": "4",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "拖拽底色",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 28985,
  "paramCode": "GT-11",
  "isVisible": "Y",
  "paramName": "远机位",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(177, 223, 246)",
  "paramValue1": "rgb(177, 223, 246)",
  "paramValue2": "甘特图",
  "paramValue3": "4",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "机位底色",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 29435,
  "paramCode": "GT-12",
  "isVisible": "Y",
  "paramName": "近机位",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(127, 204, 243)",
  "paramValue1": "rgb(127, 204, 243)",
  "paramValue2": "甘特图",
  "paramValue3": "4",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "机位底色",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 28986,
  "paramCode": "GT-13",
  "isVisible": "Y",
  "paramName": "机位未启用",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(199, 204, 207)",
  "paramValue1": "rgb(199, 204, 207)",
  "paramValue2": "甘特图",
  "paramValue3": "7",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "甘特图行底色",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 28987,
  "paramCode": "GT-14",
  "isVisible": "Y",
  "paramName": "未启用机位",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(181, 193, 203)",
  "paramValue1": "rgb(181, 193, 203)",
  "paramValue2": "甘特图",
  "paramValue3": "4",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "拖拽底色",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 28988,
  "paramCode": "GT-15",
  "isVisible": "Y",
  "paramName": "VIP航班",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(255, 159, 22)",
  "paramValue1": "rgb(255, 159, 22)",
  "paramValue2": "甘特图",
  "paramValue3": "5",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "甘特条颜色",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 28989,
  "paramCode": "GT-16",
  "isVisible": "Y",
  "paramName": "前站未起",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(229, 60, 255)",
  "paramValue1": "rgb(229, 60, 255)",
  "paramValue2": "甘特图",
  "paramValue3": "5",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "甘特条颜色",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 28990,
  "paramCode": "GT-17",
  "isVisible": "Y",
  "paramName": "前站起飞",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(16, 175, 255)",
  "paramValue1": "rgb(16, 175, 255)",
  "paramValue2": "甘特图",
  "paramValue3": "5",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "甘特条颜色",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 28991,
  "paramCode": "GT-18",
  "isVisible": "Y",
  "paramName": "本站到达",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(32, 226, 69)",
  "paramValue1": "rgb(32, 226, 69)",
  "paramValue2": "甘特图",
  "paramValue3": "5",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "甘特条颜色",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 28992,
  "paramCode": "GT-19",
  "isVisible": "Y",
  "paramName": "本站起飞",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(224, 224, 224)",
  "paramValue1": "rgb(224, 224, 224)",
  "paramValue2": "甘特图",
  "paramValue3": "5",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "甘特条颜色",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 28993,
  "paramCode": "GT-20",
  "isVisible": "Y",
  "paramName": "航空器占用",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(110, 117, 122)",
  "paramValue1": "rgb(110, 117, 122)",
  "paramValue2": "甘特图",
  "paramValue3": "5",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "甘特条颜色",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 28994,
  "paramCode": "GT-21",
  "isVisible": "Y",
  "paramName": "国内航班字体",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(51, 51, 51)",
  "paramValue1": "rgb(51, 51, 51)",
  "paramValue2": "甘特图",
  "paramValue3": "6",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "甘特图字体",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 28995,
  "paramCode": "GT-22",
  "isVisible": "Y",
  "paramName": "国际航班字体",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(0, 124, 202)",
  "paramValue1": "rgb(0, 124, 202)",
  "paramValue2": "甘特图",
  "paramValue3": "6",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "甘特图字体",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 28996,
  "paramCode": "GT-23",
  "isVisible": "Y",
  "paramName": "混合航班字体",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(51, 51, 51)",
  "paramValue1": "rgb(51, 51, 51)",
  "paramValue2": "甘特图",
  "paramValue3": "6",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "甘特图字体",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 29449,
  "paramCode": "GT-24",
  "isVisible": "Y",
  "paramName": "地区航班字体",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(0, 124, 202)",
  "paramValue1": "rgb(0, 124, 202)",
  "paramValue2": "甘特图",
  "paramValue3": "6",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "甘特图字体",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 30072,
  "paramCode": "GT-25",
  "isVisible": "Y",
  "paramName": "航空器字体颜色",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(0, 141, 113)",
  "paramValue1": "rgb(0, 141, 113)",
  "paramValue2": "甘特图",
  "paramValue3": "6",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "甘特图字体",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}, {
  "paramId": 30073,
  "paramCode": "GT-26",
  "isVisible": "Y",
  "paramName": "父子机位占用",
  "paramClassify": "gantt.colour",
  "paramValue": "rgb(245, 164, 164)",
  "paramValue1": "rgb(245, 164, 164)",
  "paramValue2": "甘特图",
  "paramValue3": "1",
  "paramValue4": null,
  "paramValue5": null,
  "remark": "拖拽底色",
  "reserved1": null,
  "reserved2": null,
  "reserved3": null
}]

export  { colorConfigArr }
